#!/bin/sh
# sudo adduser ribafs www-data
clear;
echo "Aguarde enquanto configuro as permissões do /home/ribafs/www/$1";
echo "";
find /home/ribafs/www/$1/ -type d -exec chmod 775 {} \;
find /home/ribafs/www/$1/ -type d -exec chmod ug+s {} \;
find /home/ribafs/www/$1/ -type f -exec chmod 664 {} \;
chown -R ribafs:www-data /home/ribafs/www/$1/
echo "";
echo "Concluído!";
