#!/bin/sh
# sudo adduser ribafs www-data
clear;
echo "Aguarde enquanto configuro as permissões do /var/www/html/$1";
echo "";
find /var/www/html/$1 -type d -exec chmod 755 {} \;
find /var/www/html/$1 -type f -exec chmod 654 {} \;
sudo chgrp -R www-data /var/www/html/$1/storage
sudo chgrp -R www-data /var/www/html/$1/bootstrap/cache
sudo chmod -R ug+rwx /var/www/html/$1/storage
sudo chmod -R ug+rw /var/www/html/$1/bootstrap/cache
echo "";
echo "Concluído!";
